server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.180.76:3306/db_warehouse_mysql8?serverTimezone=GMT%2b8
    username: root
    password: 1234.qwer
    multipart:
      max-file-size: 20MB
      max-request-size: 60MB
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml

config:
  jwt:
    # 密钥
    secret: abcd1234
    # token过期时间（24小时）。单位：秒.
    expire: 86400
